### ISSUE TITLE
CFI generator does not correctly count comments

### ISSUE THREAD

**Issue by Twibit** [readium/readium-cfi-js#24]
CFI generator should not count comments as a node.

http://www.idpf.org/epub/linking/cfi/epub-cfi-20111011.html#sec-path-child-ref

```html
<html>
    <p>before<!--inside-->after</p>
</html>
```

We should have the following results : 
before : /2, /1:0, /1:6
after : /2, /1:20, /1:26

But the actual results are : 
before : /2, /1:0, /1:6
after : /2, /3:0, /3:6

**Comment by danielweck** [comment]
Thank you!
Here is a more up-to-date specification link (corrected prose):
http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-path-child-ref

**Comment by danielweck** [comment]
Side question, same as https://github.com/readium/readium-cfi-js/issues/23#issuecomment-69059886
(CFI processing + matching)

**Comment by JCCR** [comment]
A fix for this has been merged.
