### ISSUE TITLE
CFI range generation with start and end at different nodes level

### ISSUE THREAD

**Issue by Twibit** [readium/readium-cfi-js#28]
The CFI generated for a selection starting and ending at different node level are incorrect.

For the following document : 
``` html
<html>
    <body>
        <h1>Title</h1>
        <p>Some <strong>very important</strong> text</p>
    </body>
</html>
```
The CFI for "important text" should be : /2/4, /2/1:5, /3:5
But the actual CFI generated is : /2/4, /2/1:5, **/4**/3:5

The CFI for "Some very" should be : /2/4, /1:0, /2/1:4
But the actual CFI generated is : /2/4, **/4**/1:0, /2/1:4

The extra step come from the parent path.

Spec : http://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-ranges

**Comment by Twibit** [comment]
Here it is !
@danielweck Yes, i'm @chardouin as well. I should get rid of one of my account :)

**Comment by JCCR** [comment]
A fix has been merged in.
