### ISSUE TITLE
getCurrentSelectionCfi() error when selection contains images

### ISSUE THREAD

**Issue by danielweck** [readium/readium-cfi-js#31]
Originally posted by @Twibit (@JCCR replied):

https://github.com/readium/readium-shared-js/issues/101

I'm trying to create annotations on selected content but when i want to get the CFI of a selection containing images, i get the following Uncaught SyntaxError.

```Uncaught SyntaxError: Expected "!/", "/", "[" or [0-9] but "," found.``` in /lib/epub_cfi.js [(1483)](https://github.com/readium/readium-shared-js/blob/master/lib/epub_cfi.js#L1483)

As a temporary workaround, i've replaced every `<img />` with a `<span />` with the image as background and the same bounds.

```javascript
$(iframe).contents().find('img').replaceWith(function(){
    return $('<span/>', {
        style: 'background-image: url('+this.src+'); background-size: '+ this.width +'px '+ this.height +'px; display:inline-block;color:transparent;',
        html: this.alt,
        width: this.width,
        height: this.height,
    });
});
```

**Comment by JCCR** [comment]
It appears that this is working now with the latest version of the CFI library, but it still won't work until the annotations_module (which implements getCurrentSelectionCfi()) is updated to reflect the latest CFI lib changes.
