### ISSUE TITLE
Problem with CFI generation in package document with namespaces.

### ISSUE THREAD

**Issue by matwood** [readium/readium-cfi-js#39]
https://github.com/readium/readium-cfi-js/blob/develop/js/cfi_generator.js#L452

When the above code looks to see the element matches 'package', and 'opf:package' will fail. I have fixed the issue by doing additional checking here:

```
 if ($parentNode.is(topLevelElement) || $currNode.is(topLevelElement) || 
                $parentNode[0].localName === topLevelElement || $currNode[0].localName === topLevelElement) {
```

Any suggestions on a better fix? If not I can submit as  PR.

**Comment by danielweck** [comment]
Seems reasonable to me, thanks!
I guess we should check whether there are other occurrences in the CFI lib, where a similar `localName` test must be done in order to match the namespace-prefixed version of the XML element name?

**Comment by matwood** [comment]
I wasn't sure if there was a regression because it seems odd this is the first time it has come up. Fixing it in this one place fixed the book I was having problems with, so I don't think it is an issue anywhere else with respect to CFI generation.

I'll put together a PR shortly.

**Comment by danielweck** [comment]
This is fixed by https://github.com/readium/readium-cfi-js/pull/61#event-1007735877
