### ISSUE TITLE
Incorrect format of CFIs generated

### ISSUE THREAD

**Issue by rkwright** [readium/readium-cfi-js#46]
From Will Gordon:

When I look thru EpubReader.js I find readium.reader.bookmarkCurrentPage in the savePlace function.
There I get:
 
{"idref":"html33","contentCFI":"/4/120,/1:0,/1:1"}
 
{"idref":"html","contentCFI":"/4/2/2,/1:0,/1:1"}
 
{"idref":"titlepage","contentCFI":"/4/2/2"}
 
These aren’t quite in epubcfi format.
CFI Specifications:  http://www.idpf.org/epub/linking/cfi/epub-cfi.html
 
The Service does a validation check so my calls are failing.
Regexpression used for validation: (epubcfi)(\()(\/\d*[02468])(\/\d*[02468])(\[\S*\])?(!)((\/\d*[02468])(\[\S*\])?)(\S*)(\))
 
For now I’m just trying to get where the user left off in the book.  Later I’ll need the highlight location, etc.
 
Is there a place in the code that gives me the correct epubcfi?
For example, epubcfi(/6/4[chap01ref]!/4[body01]/10[para05]/2/1:3)

**Comment by danielweck** [comment]
Duplicate https://github.com/readium/readium-cfi-js/issues/12
