### ISSUE TITLE
Using CFI js with readium viewer js.

### ISSUE THREAD

**Issue by sureshmuttagi** [readium/readium-cfi-js#6]
hi,
I have installed n run all the set up for development of CFI. Now I am reading epub files using readium-js-viewer library. I am planning for text highlighting in the reader. So i want to use CFI to store the highlighted text. My problem is I am not getting how to generate CFI for a file. Please let me know how and from where I can start the coding for generating CFI in readium-js-viewer library. Thanks in advance.....

**Comment by JCCR** [comment]
Closed due to inactivity. Please re-open if you would still like this to be answered. We are in the process of improving our documentation. Thanks.
