### ISSUE TITLE
[Question] CFI comparison

### ISSUE THREAD

**Issue by aigori** [readium/readium-cfi-js#62]
Is there a way to compare between two CFIs? I mean which CFI is prior to the other. I couldn't find any function does it. Although I think it cannot be clear task since there are lots of problems(e.g. range CFI, assertion, spacial offset etc.), but do you know how to compare CFIs in simple way?

**Comment by JCCR** [comment]
I believe we have a simple implementation for this somewhere in another codebase.
"readium-js-viewer" perhaps

I'll double check. I believe @danielweck originally made it.

**Comment by danielweck** [comment]
Look for usages of the `cfiIsBeforeOrEqual()` function in the `epub3MultipleRenditions` feature branch:
https://github.com/readium/readium-shared-js/blob/feature/epub3MultipleRenditions/js/models/multiple_renditions.js#L104

**Comment by danielweck** [comment]
...but as you can see, this applies to a limited subset of CFI expressions, and the `cfiTokenise()` function has not been heavily tested:
https://github.com/readium/readium-shared-js/blob/feature/epub3MultipleRenditions/js/models/multiple_renditions.js#L79

**Comment by aigori** [comment]
Thank you for your answer. I tested your functions and they work fine for most cases, but do not cover with range CFI, and spatial/character offsets, etc.

If I make some improvements, I'll let you know.

**Comment by danielweck** [comment]
Thanks!

**Comment by danielweck** [comment]
Character offset comparison now supported:
https://github.com/readium/readium-cfi-js/pull/67

**Comment by aigori** [comment]
Thanks!  In fact, my CFI comparison code had bugs and restrictions to use for some cases.
Thank you for everything!

**Comment by JCCR** [comment]
closing :)
