### ISSUE TITLE
npm run prepare:all not working properly

### ISSUE THREAD

**Issue by Nalinc** [readium/readium-cfi-js#63]
Hello,

Please note that `npm run prepare:all` is not working as desired.
In the following line in `package.json`,
```
"prepare:local": "npm outdated || echo outdated && npm install --no-save --only=prod && npm install --no-save --only=dev && npm update --no-save && npm run prepare:local:common",
```
Probably the **||** used after `npm outdated` is not allowing the rest of the command to get executed. I know this for sure as the following command was running successfully when I ran it separately.
```
npm install --no-save --only=prod && npm install --no-save --only=dev && npm update --no-save && npm run prepare:local:common 
``` 

but the flow never reached here while using `npm run prepare:all`

Similar issue is present in rest of the readium-* projects(readium-js, readium-shared-js, readium-js-viewer)

**Comment by danielweck** [comment]
This is working fine at my end, on Windows, Linux and OSX. What npm version?

**Comment by Nalinc** [comment]
npm 3.10.5 and node 6.10.3

**Comment by danielweck** [comment]
I think this is fixed in the develop branch, please check. Many thanks for reporting!
